### ISSUE TITLE
MD: Slicing UI Testimoni Detail Page

### ISSUE THREAD

**Issue by antoniluthfi** [Lumos-IL-Massive-Project/lapak-event-mobile-app#1]
Figma Link: https://www.figma.com/file/ky5DRTdbYnrPYOgXQSDLbh/Event-Organizer---Mobile?type=design&node-id=534-5945&mode=design&t=DneQ8XD6MOULgYoU-4

**Comment by abdussalam21** [comment]
Link PR: https://github.com/Lumos-IL-Massive-Project/lapak-event-mobile-app/pull/6
