### ISSUE TITLE
MD: Create PPT for Sprint Review 1

### ISSUE THREAD

**Issue by antoniluthfi** [Lumos-IL-Massive-Project/lapak-event-mobile-app#10]

**Comment by Asfiaapriani** [comment]
Sudah selesai yah tinggal besok untuk di presentasikan, 

- link ppt : https://www.canva.com/design/DAFxndXuGvc/_9cSSmmZjRTvzcQteF6KoQ/edit?utm_content=DAFxndXuGvc&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton                                               

- story telling
 mengembangkan sebuah pemesanan acara online yang disebut "Lapak Event" di bawah naungan tim Lumos. siapa aja si tim lumos itu??  (sebutkn nama namanya) ini bertujuan untuk membantu orang-orang, yang terlalu sibuk dengan pekerjaan sehingga tidak dapat mengatur acaranya sendiri. Dengan lapak Event, pengguna dapat mengakses platform kapanpun dan dimanapun untuk memesan penyelenggara acara. Platform ini menawarkan berbagai opsi tepercaya dan andal, memungkinkan pengguna mewujudkan impian acara mereka. Lapak Event juga memberikan ulasan informatif untuk membantu klien mengambil keputusan yang lebih baik dan meminimalkan kegagalan perencanaan acara. Visi lapak Event adalah untuk menjamin keamanan, kenyamanan, dan pengalaman berkesan bagi kliennya. Individu yang tertarik didorong untuk bergabung dengan komunitas lapak Event di bawah tim Lumos. connest us juga sebuah website didalam website tersebut untuk Menyediakan sebuah website portal office untuk melakukan pengolaan data EO maupun Costumer. website ini akan mengelola semua data mulai dari data costumer, data EO, data transaksi, memantau akun customer
