### ISSUE TITLE
Create Poster "Local Heroes"

### ISSUE THREAD

**Issue by antoniluthfi** [Lumos-IL-Massive-Project/lapak-event-mobile-app#16]
Telolet telolet....🚌🚎
Gubrakk!!!💥 Ada info penting niih

Sehubungan dengan Hari Pahlawan ditanggal 10 November 2023, ada challenge baru nih untuk kita semuaa! Challenge apatuuu👀?

Jenngg jengg...
✨Desain Poster dengan tema Local Heroes✨

Teman-teman dapat berkreasi sekreatif mungkin untuk menghighlight Local Heroes versi kalian! 🦸‍♂️🦸‍♀️ Sistemasinya adalah:
Poster dikerjakan secara kelompok massive (merge ataupun nonmerge)
Ukuran poster A4
Resolusi 300 dpi
Format pengumpulan PDF
Sertakan judul dan deskripsi karya

Makna "local heroes" disini bukan harus pahlawan ya temen-temen, bisa aja orang-orang yang menurut kalian pahlawan disekitar kalian.

Dan akan ada quiz yang seru banget nihh nanti! Deadline pengumpulan poster sampai hari Kamis, jam 17.00 WIB, link pengumpulan menyusul yaa 😊😊

**Comment by lstiara** [comment]
Poster Name : Great Dad
Description : Tentang seorang ayah yang melindungi kita dari apapun dan selalu berada di garis terdepan.

![Image](https://github.com/Lumos-IL-Massive-Project/lapak-event-mobile-app/assets/145951555/a4b550b2-71c2-4dfb-8f09-6400974fe809)
