### ISSUE TITLE
MD: Slicing UI Modal Filter

### ISSUE THREAD

**Issue by antoniluthfi** [Lumos-IL-Massive-Project/lapak-event-mobile-app#2]
Figma Link: https://www.figma.com/file/ky5DRTdbYnrPYOgXQSDLbh/Event-Organizer---Mobile?type=design&node-id=1050-2400&mode=design&t=DneQ8XD6MOULgYoU-4

**Comment by adityamufid** [comment]
Link pull request: https://github.com/Lumos-IL-Massive-Project/lapak-event-mobile-app/pull/11
