### ISSUE TITLE
Create Questionnaire for EO and User

### ISSUE THREAD

**Issue by antoniluthfi** [Lumos-IL-Massive-Project/lapak-event-mobile-app#23]

**Comment by Asfiaapriani** [comment]
hasil wawancara bersama EO( Tintin Rias) terkait aplikasi EO ituh beliau pada intinya bilang bahwasanya dengan aplikasi yang kita bikin lebih mempermudah EO dalam mencari pelanggan kaarena kan ini posisi EO yang berada di desa otomatis orang lain kenal eo ituh dari satu orang ke orang lain sehingga cakupan nya untuk mencari pelanggan itu belum luas.

**Comment by adeliasf25** [comment]
![Uploading 014D040C-63C2-4E93-8A9E-78C71F59EC1F.jpeg…]()

**Comment by adeliasf25** [comment]
hasil wawancara bersmaa Gswara sebuah EO yang ada di Kota Semarang dia memiliki goals untuk menjangkau client di seluruh Indonesia. Serta tertarik dengan aplikasi ini karena keamanannya dalam transaksi, jadi meminimalisis client yang kabur begitu saja. Sarannya dalam warna kurang menyala.

**Comment by mutianandika** [comment]
Hasil wawancara dengan Nenden Hopipah, seorang pekerja di bidang Event Organizer (EO), menyatakan bahwa menurutnya keberadaan aplikasi sangat membantu dalam mencari informasi seputar jasa EO, jenis layanan yang tersedia, dan keterlibatan dalam acara. Penggunaan aplikasi membuat interaksi dengan pelanggan menjadi lebih mudah dan efisien. Adanya aplikasi ini juga mempermudah proses pencarian vendor atau layanan yang sesuai dengan preferensi pelanggan. Nenden berharap bahwa kehadiran aplikasi ini dapat memberikan dukungan dalam pemasaran EO-nya dan memungkinkan mereka untuk menyesuaikan layanan sesuai dengan keinginan pelanggan.

**Comment by abdussalam21** [comment]
Hasil Wawancara dengan Muhammad Al Madani selaku pekerja di bidang Event Organizer (EO) adalaah, dia menyampaikan kesulitan kesulitan yg dia alami ketika bekerja sebagai EO. dia berharap aplikasi ini dapat membantu menyelesaikan kesulitan yg dialaminya seperti sulitnya mencari client, fitur yg memudahkan berkomunikasi dengan client yang kadang keinginaya suka ber ubah-ubah, memudahkan proses pitching project saat memasarkannya, dapat berkoordinasi dengan baik oleh vendor dan beberapa pihak venue, menyediakan fitur untuk meminimalisir terjadinya miss komunikasi antara beberapa pihak.
