### ISSUE TITLE
Create Virtual Background Image for Sprint Review

### ISSUE THREAD

**Issue by antoniluthfi** [Lumos-IL-Massive-Project/lapak-event-mobile-app#34]

**Comment by vikaDwi** [comment]
![Image](https://github.com/Lumos-IL-Massive-Project/lapak-event-mobile-app/assets/146110212/8e4c1f36-9efa-4f9d-b195-2082b91269db)



![Image](https://github.com/Lumos-IL-Massive-Project/lapak-event-mobile-app/assets/146110212/6cc3f18b-1145-42dc-a154-a010c08f0303)
